/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

*/
pub struct Solution {}
impl Solution {
    pub fn find_the_difference(s: String, t: String) -> char {
        
    }
}

fn main() {
  assert_eq!(0, Solution::find_the_difference(0));
  println!("Pass test cases!");
}
